import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';
import {AreaChart,Area,BarChart,Bar as B,XAxis,YAxis,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {activity,brands} from '../data/mock';import {threatApi} from '../services/api';import {Metric,RiskBadge,Demo} from '../components/ui';
export default function Dashboard(){
  const [t,setT]=useState([]);useEffect(()=>{threatApi.list().then(setT)},[]);
  return <div className="space-y-6"><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">Intelligence overview</h1><Demo/></div>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-6"><Metric label="Total scans" value="12,480"/><Metric label="High-risk targets" value="1,204" tone="text-orange-500"/><Metric label="QR scans" value="3,912"/><Metric label="Active campaigns" value="2" tone="text-red-500"/><Metric label="Brands impersonated" value="14"/><Metric label="Confirmed threats" value="86" tone="text-red-500"/></div>
  <div className="grid gap-4 lg:grid-cols-3"><div className="panel p-4 lg:col-span-2"><h2 className="mb-2 font-medium">Threat activity · last 7 days</h2><div className="h-64"><ResponsiveContainer><AreaChart data={activity}><XAxis dataKey="d"/><YAxis/><Tooltip/><Legend/>
   <Area dataKey="safe" stackId="a" stroke="#10b981" fill="#10b98155"/><Area dataKey="suspicious" stackId="a" stroke="#f59e0b" fill="#f59e0b55"/><Area dataKey="high" stackId="a" stroke="#f97316" fill="#f9731655"/><Area dataKey="critical" stackId="a" stroke="#dc2626" fill="#dc262655"/></AreaChart></ResponsiveContainer></div></div>
  <div className="panel p-4"><h2 className="mb-2 font-medium">Most targeted brands</h2><div className="h-64"><ResponsiveContainer><BarChart data={brands} layout="vertical"><XAxis type="number"/><YAxis dataKey="b" type="category" width={70}/><Tooltip/><B dataKey="n" fill="#0891b2"/></BarChart></ResponsiveContainer></div></div></div>
  <div className="panel overflow-x-auto"><table className="w-full text-sm"><caption className="p-3 text-left font-medium">Recent threats</caption><thead className="text-left text-xs text-slate-500"><tr>{['Target','Type','Brand','Risk','Detected','Reports','Status',''].map(h=><th key={h} className="px-3 py-2">{h}</th>)}</tr></thead>
  <tbody>{t.slice(0,5).map(r=><tr key={r.id} className="border-t border-slate-200 dark:border-ink-700"><td className="px-3 py-2 font-mono text-xs">{r.target}</td><td className="px-3">{r.type}</td><td className="px-3">{r.brand}</td><td className="px-3"><RiskBadge score={r.risk}/></td><td className="px-3">{r.last}</td><td className="px-3">{r.reports}</td><td className="px-3">{r.status}</td><td className="px-3"><Link className="text-cyan-600 underline" to={`/report/${r.id}`}>Investigate</Link></td></tr>)}</tbody></table></div></div>}
